# Generated by Django 5.0.6 on 2024-07-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
