# Generated by Django 5.0.6 on 2024-07-22 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_address_customuser_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='time',
        ),
    ]
