# Generated by Django 5.0.6 on 2024-07-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_blood_customuser_role_alter_appointment_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
