# Generated by Django 5.0.6 on 2024-07-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ghana_card_id',
            new_name='national_id',
        ),
    ]
