# Generated by Django 5.0.6 on 2024-07-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='hospitalName',
            new_name='Hospital',
        ),
    ]
