# Generated by Django 5.0.6 on 2024-07-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_rename_hospitalname_customuser_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Hospital',
            field=models.CharField(max_length=50),
        ),
    ]
