# Generated by Django 5.0.6 on 2024-07-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_alter_hospital_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
